{
 "title": "Buatan Adnan 🙇🏻‍♂️",
 "description": "Postgres Replication and Detail",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "label": "source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(pg_up,job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(pg_replication_is_replica,instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Status Slot Active",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_replication_slots_active{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_replication_is_replica{job=\"$job\"} == 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Wal Sender",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_senders{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slot Active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "pg_replication_slots_active{job=\"$job\"}",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Current wal sender",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_replication_pg_wal_lsn_diff{job='$job'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Connections $instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{instance=~\"$instance\", job=\"$job\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wal LSN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "pg_replication_slots_pg_wal_lsn_diff{job=\"$job\"} / 1048576",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Lock",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "pg_locks_count{job=\"$job\"} != 0",
     "legendFormat": "{{datname}} - {{mode}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Current Connected Backend",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{job=\"$job\",instance=~\"$instance\"} != 0",
     "legendFormat": "{{instance}} - {{datname}}"
    }
   ]
  }
 ]
}