{
 "title": "Loki Postgres KP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "loki" },
   {
    "name": "vm",
    "label": "vm",
    "query": {}
   },
   {
    "name": "user",
    "label": "user",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Query Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query more than 1000",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(user) (count_over_time({job=\"patroni\", host_vm=~\"$vm\", user=~\"$user\"} | regexp `.* duration: (?P<duration>[0-9\\\\.]+) .*: (?P<query_type>[a-zA-Z]+)` | duration >= 1000 [$__auto]))",
     "legendFormat": "{{user}}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Query more than 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(user) (count_over_time({job=\"patroni\", host_vm=~\"$vm\", user=~\"$user\"} | regexp `.* duration: (?P<duration>[0-9\\\\.]+) .*: (?P<query_type>[a-zA-Z]+)` | duration >= 500 | duration < 1000 [$__auto]))",
     "legendFormat": "{{user}}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Log query more than 1000",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"patroni\", host_vm=~\"$vm\", user=~\"$user\"} | regexp `.* duration: (?P<duration>[0-9\\\\.]+) .*: (?P<query_type>[a-zA-Z]+)` | duration >= 1000",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Log query more than 500",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"patroni\", host_vm=~\"$vm\", user=~\"$user\"} | regexp `.* duration: (?P<duration>[0-9\\\\.]+) .*: (?P<query_type>[a-zA-Z]+)` | duration >= 500 | duration < 1000",
     "maxLines": 100
    }
   ]
  },
  { "title": "Log Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "FATAL Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"patroni\",host_vm=~\"$vm\",user=~\"$user\"} |= `FATAL` [5m]))",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "ERROR Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"patroni\",host_vm=~\"$vm\",user=~\"$user\"} |= `ERROR` [5m]))",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "FATAL Log",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"patroni\", host_vm=~\"$vm\", user=~\"$user\"} |= `FATAL`"
    }
   ]
  },
  {
   "title": "ERROR Log",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"patroni\", host_vm=~\"$vm\", user=~\"$user\"} |= `ERROR`"
    }
   ]
  }
 ]
}